[package]
name = "smart-dl-provider"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
smart-dl-core = { path = "../core" }
md-5 = "0.10"
sha1 = { workspace = true }

[dev-dependencies]
axum = "0.7"
tempfile = "3"
smart-dl-httpdl = { path = "../httpdl" }